# Generated by Django 4.0.4 on 2022-05-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.IntegerField(choices=[[0, 'Ninguno'], [1, 'Cuerdas'], [2, 'Percusión'], [3, 'Amplificadores'], [4, 'Accesorios']], null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
