# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestT1Agregaralcarro():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_t1Agregaralcarro(self):
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.set_window_size(1936, 1056)
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(2) > a").click()
    assert self.driver.find_element(By.ID, "titulo").text == "PRODUCTOS"
    self.driver.find_element(By.LINK_TEXT, "Agregar al Carrito").click()
    self.driver.find_element(By.XPATH, "(//a[@onclick=\'showAlert()\'])[6]").click()
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(3) > a").click()
    assert self.driver.find_element(By.ID, "carro").text == "CARRITO"
    assert self.driver.find_element(By.ID, "3").text == "Guitarra Mercury MSM02"
    assert self.driver.find_element(By.ID, "8").text == "Accesorios Vocal Studio Pro"
  
